# Generated by Django 5.0.6 on 2026-08-04 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('sales', 'Sales'), ('manual_payment', 'Manual Order Payment'), ('inventory_purchase', 'Inventory Purchase'), ('delivery', 'Delivery / Logistics'), ('marketing', 'Marketing'), ('salary', 'Salary / Staff'), ('refund', 'Refund'), ('misc', 'Miscellaneous')], default='misc', max_length=25),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_type', 'income')), fields=('related_order',), name='unique_income_transaction_per_order'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('category', 'refund')), fields=('related_order',), name='unique_refund_transaction_per_order'),
        ),
    ]
