# Generated by Django 5.0.6 on 2026-07-31 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Shown in the top banner, e.g. 'Diwali Dhamaka'.", max_length=150)),
                ('offer_type', models.CharField(choices=[('buy_x_get_y', 'Buy X Get Y'), ('amount_discount', 'Spend X, Get Y Off / Free')], max_length=20)),
                ('description', models.CharField(blank=True, help_text='Short banner text.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority offers are evaluated first at checkout.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyXGetYOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_quantity', models.PositiveIntegerField(default=1)),
                ('get_quantity', models.PositiveIntegerField(default=1)),
                ('buy_products', models.ManyToManyField(help_text="Products that count towards the 'buy' quantity.", related_name='buy_x_offers', to='products.product')),
                ('free_products', models.ManyToManyField(blank=True, help_text='Products eligible to be given free. Leave empty to make the bought product itself free.', related_name='get_y_offers', to='products.product')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buy_x_get_y', to='offers.offer')),
            ],
        ),
        migrations.CreateModel(
            name='AmountDiscountOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_type', models.CharField(choices=[('flat_discount', 'Flat Rupee Discount'), ('free_products_worth', 'Free Products Worth ₹')], max_length=25)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Rupees off, or rupee-value of products the customer may pick free.', max_digits=10)),
                ('applicable_products', models.ManyToManyField(blank=True, help_text='Products whose value counts toward the minimum. Leave empty to apply to the whole cart.', related_name='amount_discount_offers', to='products.product')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amount_discount', to='offers.offer')),
            ],
        ),
    ]
