# Generated by Django 5.0.6 on 2026-08-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Shown in the storefront offer carousel.', null=True, upload_to='offers/'),
        ),
    ]
