# Generated by Django 5.0.6 on 2026-08-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_banner_image'),
        ('products', '0002_cataloguefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountdiscountoffer',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, help_text='Products this offer applies to. Leave empty to apply to the whole cart / all products.', related_name='amount_discount_offers', to='products.product'),
        ),
        migrations.AlterField(
            model_name='amountdiscountoffer',
            name='discount_type',
            field=models.CharField(choices=[('flat_discount', 'Flat Rupee Discount'), ('free_products_worth', 'Free Products Worth ₹'), ('percentage_discount', 'Percentage Discount')], max_length=25),
        ),
        migrations.AlterField(
            model_name='amountdiscountoffer',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='Rupees off, rupee-value of products the customer may pick free, or a percentage (0-100) — depends on Discount Type.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='amountdiscountoffer',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
