# Generated by Django 5.0.6 on 2026-07-31 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_called', models.BooleanField(default=False)),
                ('was_answered', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('not_called', 'Not Called Yet'), ('no_answer', 'Called — No Answer'), ('answered', 'Called — Answered'), ('interested', 'Interested / Proceeding'), ('not_interested', 'Not Interested'), ('deal_closed', 'Deal Closed — Paid'), ('cancelled', 'Cancelled')], default='not_called', max_length=20)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='customers.customer')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='orders.order')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
