# Generated by Django 5.0.6 on 2026-08-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_alter_calllog_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('not_called', 'Not Called Yet'), ('no_answer', 'Called — No Answer'), ('answered', 'Called — Answered'), ('deal_closed', 'Deal Closed — Paid'), ('cancelled', 'Cancelled')], default='not_called', max_length=20),
        ),
    ]
